### ISSUE TITLE
Fake serial key popup

### ISSUE THREAD

**Issue by BlitW0** [J2TEAM/idm-trial-reset#12]
A few days ago, the trial reset stopped working, so I tried the register button to see if it worked. IDM started showing the popup shown below:

<p align="center">
<img src="https://idmregistrator.files.wordpress.com/2018/07/fserial_thumb.png?w=632"/>
</p>

I tried various tools to reset the registry values to their default values, for e.g. idm_reset.reg from this repository and IDM_cleaner.bat written by CHEF-KOCH. It was still showing the popup, even after I chose full uninstall and reinstalled it from scratch. Could you please point me to the registry values to change or any tool that could help me get rid of this popup?

**Comment by 0xearl** [comment]
i think it's because of the IDM update it keeps bugging me too, but if that isnt the issue. for the tool to work you need to run it on admin permission
