### ISSUE TITLE
Error on Version 6.38 Build 2

### ISSUE THREAD

**Issue by SR-7** [J2TEAM/idm-trial-reset#13]
![image](https://user-images.githubusercontent.com/41051374/92301724-94e00c00-ef98-11ea-856f-313b513fd82c.png)

Getting this error, any idea why?

**Comment by priyanshuga** [comment]
Search on google UxTheme.dll and download it and place in that folder. I guess then it will work fine.

**Comment by shockergit** [comment]
Works fine here. Try to reinstall
