### ISSUE TITLE
Source code of SetACLx32.exe and SetACLx64.exe???

### ISSUE THREAD

**Issue by navaneethkm004** [J2TEAM/idm-trial-reset#16]
Where are the source codes of SetACLx64.exe and SetACLx32.exe?

**Comment by J2TEAM** [comment]
Please see the credit section in README.md

![image](https://user-images.githubusercontent.com/5250117/128112699-a64f84f8-119f-45f5-9a1a-4214d6717929.png)

It means that I am not the author of those 2 files. And maybe those files aren't open source either.
