### ISSUE TITLE
please updtae the app it's been years now

### ISSUE THREAD

**Issue by fisforfaheem** [J2TEAM/idm-trial-reset#17]

**Comment by rsmyst** [comment]
> _No description provided._

why would an update be needed for an app that still works like it was intended to on day 1?

**Comment by fisforfaheem** [comment]
it should be updated to match latest Ui and etc



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
02/07/22,
01:05:49 AM

**Comment by Hacker-bobo** [comment]
虽然没有更新，但是依然能用，真的太厉害了！

**Comment by Lgazana** [comment]
@fisforfaheem Nice trackers man

**Comment by fisforfaheem** [comment]
yes :) it works  but if u got time...do update it with some better UI etc



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
02/28/22,
01:50:09 PM
