### ISSUE TITLE
Why your software connects to pastebin?

### ISSUE THREAD

**Issue by Baddani** [J2TeaM/idm-trial-reset#2]
Why your software connects to pastebin????

**Comment by J2TeaM** [comment]
As you can see, it is for the purpose of updating the new version.

https://github.com/J2TeaM/idm-trial-reset/search?utf8=%E2%9C%93&q=pastebin&type=

http://pastebin.com/raw/uYr0cstV

![image](https://user-images.githubusercontent.com/5250117/38714280-959ed816-3eff-11e8-8da1-ccc3a28e0e01.png)
