### ISSUE TITLE
Trojan Detected

### ISSUE THREAD

**Issue by ParaDoxx619** [J2TEAM/idm-trial-reset#32]
I scanned it with an anti virus toll & its showing Trojan detected.

**Comment by rezzvy** [comment]
Either your downloaded file is infected, or antivirus you're using is incorrectly marking it as a virus (false detection). Additionally, this app likely accesses app configuration, which could trigger antivirus warnings in some cases.

**Comment by Bug-Cache** [comment]
its clean

https://www.virustotal.com/gui/file/80b98a2f072ca3ce98ec90334d254c31bcab321a29db5cb69aa37e3be475b6de?nocache=1

![image](https://github.com/J2TEAM/idm-trial-reset/assets/98657967/06073e92-5c99-4674-9234-327d2dfd9d89)

**Comment by gengooro** [comment]
![image](https://github.com/J2TEAM/idm-trial-reset/assets/128297159/325fdd81-8ac8-4245-9394-07162bb0c6b7)
yeh it has trojan

**Comment by Ajaythepower1606** [comment]
![Screenshot 2023-10-20 155711](https://github.com/J2TEAM/idm-trial-reset/assets/59187057/330c2310-5bff-477f-8d79-4ebb5a8ff76e)
it has trojon but can we remove the virus from the file then use it !?

**Comment by Ajaythepower1606** [comment]
> ![image](https://user-images.githubusercontent.com/128297159/270909299-325fdd81-8ac8-4245-9394-07162bb0c6b7.png) yeh it has trojan

i tried virus total now and found the above result ... so there are now more viruses in it

**Comment by reybars** [comment]
so am I fuck up?

**Comment by J2TEAM** [comment]
No need to worry about AutoIt being mistaken for malware. You can compile it yourself from the source code on GitHub.
