### ISSUE TITLE
Pop up issue 

### ISSUE THREAD

**Issue by MustafaEsatTemel** [J2TEAM/idm-trial-reset#33]
How can i remove this pop up. Its sometimes pop up.
![image](https://github.com/J2TEAM/idm-trial-reset/assets/65919257/6671d3ff-2d1b-4a0c-9e61-fc468b60cfb2)

**Comment by ahmadshakeel350** [comment]
came here to look for the solution to fix this popup but i guess not fixed yet.

**Comment by Amature123** [comment]
> How can i remove this pop up. Its sometimes pop up. ![image](https://private-user-images.githubusercontent.com/65919257/275973123-6671d3ff-2d1b-4a0c-9e61-fc468b60cfb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyOTcyNDMsIm5iZiI6MTcwNzI5Njk0MywicGF0aCI6Ii82NTkxOTI1Ny8yNzU5NzMxMjMtNjY3MWQzZmYtMmQxYi00YTBjLTllNjEtZmM0NjhiNjBjZmIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDA5MDkwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxNjcyZWI4ZjMzOTYwMDVkNzJlMTZjNmViZDE4ZmM1Yjc0MTFhNGIxZTc2ZTE1YThiZmRiYWI1MWFiODMxNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mx7z044Kupnbzs28DLQFjlBPcbKISZPjb6Hzt04ydu4)

same :')
