### ISSUE TITLE
WTF!It has malware 

### ISSUE THREAD

**Issue by CartickKazama** [J2TEAM/idm-trial-reset#34]
virustotal clarified it as a malware do not install!

**Comment by Mr-Nobody1** [comment]
really?

**Comment by Mr-Nobody1** [comment]
I just did. Maybe I messed up?

**Comment by rozari0** [comment]
No, it doesn't. Anti-virus detect this as malware because it modify registry. 
But yeah, buy a license so you don't have to worry about malware .

**Comment by J2TEAM** [comment]
No need to worry about AutoIt being mistaken for malware. You can compile it yourself from the source code on GitHub.
