### ISSUE TITLE
Does this support being run from the command line?

### ISSUE THREAD

**Issue by Jake1702** [J2TEAM/idm-trial-reset#5]

**Comment by amidevous** [comment]
download file

https://github.com/J2TEAM/idm-trial-reset/raw/master/src/idm_trial.reg

regedit /S idm_trial.reg

**Comment by J2TEAM** [comment]
Yes, see: https://github.com/J2TEAM/idm-trial-reset/blob/master/src/IDM%20Trial%20Reset.au3#L24-L34
