### ISSUE TITLE
Many Antivirus say file is not safe to use

### ISSUE THREAD

**Issue by rajnishdubey3** [J2TEAM/idm-trial-reset#7]
Hello,

I just made a scan at "https://www.virustotal.com/gui/home/upload" and it says file is not safe to use. 
Can you provide comment on this?

Why this file is not safe?

Rajnish Dubey

**Comment by J2TEAM** [comment]
AutoIt usually get false positives by AV. Read more about this problem: https://www.autoitscript.com/wiki/AutoIt_and_Malware

Btw, this is a duplicate issue. See #6.
